Kerrgo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
import userprofile.views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/signup/$", userprofile.views.SignupView.as_view(), name="account_signup"),
    url(r"^account/", include("account.urls")),
    url(r'^messages/', include('postman.urls')),
    url(r'^',include('mainsite.urls', namespace="mainsite")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.conf.urls import include,url
# from . import views
from . import views
from django.views.generic import TemplateView

urlpatterns = [
	#url(r'^search/?$', views.MySearchView.as_view(), name='mysearch'),
	url(r'^search/?$', views.my_basic_search, name="mysearch"),
	# url(r'^search/', include('haystack.urls')),
	url(r'^viewcompany/(?P<goal>[\w|\W]+)/(?P<company_id>[0-9]+)/$',views.viewCompany, name='viewCompany'),
	url(r'^investor/(?P<user_id>[0-9]+)/$',views.viewInvestor, name='viewInvestor'),
	url(r'^investors/(?P<type_name>[\w|\W]+)/$',views.browseInvestor, name='browseInvestor'),
	url(r'^companies/(?P<goal_name>[\w|\W]+)/$',views.browseCompany, name='browseCompany'),
	url(r'^dashboard/?$', views.dashboard, name="dashboard"),
	url(r'^dashboard_investor/?$', views.dashboard_investor, name="dashboard_investor"),
	url(r'^dashboard_admin/?$', views.dashboard_admin, name="dashboard_admin"),
	url(r'^editprofile/?$', views.editProfile_company, name="editProfile_company"),
	url(r'^editprofile_investor/?$', views.editProfile_investor, name="editProfile_investor"),
	url(r'^investor_admin/(?P<investor_id>[0-9]+)/$', views.editInvestors_admin, name="editInvestors_admin"),
	url(r'^addinvestor_admin/?$', views.addInvestors_admin, name="addInvestors_admin"),
	url(r'^addcompany_admin/(?P<goal>[\w|\W]+)/$', views.addCompany_admin, name="addCompany_admin"),
	url(r'^company_admin/(?P<goal>[\w|\W]+)/(?P<company_id>[0-9]+)/$', views.editCompany_admin, name="editCompany_admin"),
	url(r'^viewmyprofile/?$', views.viewMyprofile_company, name="viewmyProfile_company"),
	url(r'^viewmyprofile_investor/?$', views.viewMyprofile_investor, name="viewmyProfile_investor"),
	url(r'^goal/?$', views.goalChoose, name="goalChoose"),
	url(r'^deletefile/(?P<goal>[\w|\W]+)/(?P<fid>[0-9]+)/$', views.deleteFile, name="deleteFile"),
	url(r'^google22cffa4b9737b2ae.html',TemplateView.as_view(template_name='mainsite/google22cffa4b9737b2ae.html'),)
]

Kerrgo/templates/search/search.html
{% extends 'site_base.html' %}
{% load i18n pagination_tags %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block body %}
<div class="container">
    <h2>Search</h2>

    <form role="form" method="get" action="{% url 'mainsite:mysearch' %}">
    <div class="row">
        <div class="form-group col-md-4">
            {% render_field form.category class="form-control" %}
        </div>
        <div class="form-group col-md-4">
            {% render_field form.goal class="form-control" %}
        </div>
        <div class="form-group input-group col-md-4">
            {% render_field form.q class="form-control" placeholder="Search for..."%}
            <span class="input-group-btn">
                <input type="submit" class="btn btn-default" value="Search" />
                <!-- <button class="btn btn-default" type="button">Go!</button> -->
            </span>
        </div>
    </div>
    </form>

    {% if query %}
        <h3>{{ results.count }} Results are found</h3>

        {% autopaginate results 6 %}
        {% if invalid_page %}
        <p>{% trans "Sorry, this page number is invalid." %}</p>
        {% else %}
            {% if results %}
                {% for r in results %}
                    {% if forloop.counter0|divisibleby:"3" %} <div class="row"> {% endif %}
                        <div class="col-md-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <b>{{r.object.company.myprofile.fullname}}</b>
                                    <div class="pull-right text-success"><small>{{r.object.goal.goal}} </small></div>
                                </div>
                                <div class="panel-body">
                                    <p class = "col-md-12">{{r.object.shortDescription|truncatewords_html:40}}</p>
                                </div>
                                <div class="panel-footer">
                                    <a href="{% url 'mainsite:viewCompany' r.object.company.id %}" class="btn btn-outline btn-success col-md-offset-4" target="_blank">View Details</a>
                                </div>
                            </div>
                        </div>
                    {% if forloop.counter|divisibleby:"3" or forloop.last %} </div>{% endif %}
                    {% endfor %}
            {% endif %}
        
        {% endif %}
    <!-- Pager -->
    <nav>
    {% paginate %}
    </nav>
    {% else %}
        {# Show some example queries to run, maybe query syntax, something else? #}
    {% endif %}
</div>
{% endblock %}