Kerrgo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
import userprofile.views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/signup/$", userprofile.views.SignupView.as_view(), name="account_signup"),
    url(r"^account/", include("account.urls")),
    url(r'^messages/', include('postman.urls')),
    url(r'^',include('mainsite.urls', namespace="mainsite")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.conf.urls import include,url
# from . import views
from . import views
from django.views.generic import TemplateView

urlpatterns = [
	#url(r'^search/?$', views.MySearchView.as_view(), name='mysearch'),
	url(r'^search/?$', views.my_basic_search, name="mysearch"),
	# url(r'^search/', include('haystack.urls')),
	url(r'^viewcompany/(?P<goal>[\w|\W]+)/(?P<company_id>[0-9]+)/$',views.viewCompany, name='viewCompany'),
	url(r'^investor/(?P<user_id>[0-9]+)/$',views.viewInvestor, name='viewInvestor'),
	url(r'^investors/(?P<type_name>[\w|\W]+)/$',views.browseInvestor, name='browseInvestor'),
	url(r'^companies/(?P<goal_name>[\w|\W]+)/$',views.browseCompany, name='browseCompany'),
	url(r'^dashboard/?$', views.dashboard, name="dashboard"),
	url(r'^dashboard_investor/?$', views.dashboard_investor, name="dashboard_investor"),
	url(r'^dashboard_admin/?$', views.dashboard_admin, name="dashboard_admin"),
	url(r'^editprofile/?$', views.editProfile_company, name="editProfile_company"),
	url(r'^editprofile_investor/?$', views.editProfile_investor, name="editProfile_investor"),
	url(r'^investor_admin/(?P<investor_id>[0-9]+)/$', views.editInvestors_admin, name="editInvestors_admin"),
	url(r'^addinvestor_admin/?$', views.addInvestors_admin, name="addInvestors_admin"),
	url(r'^addcompany_admin/(?P<goal>[\w|\W]+)/$', views.addCompany_admin, name="addCompany_admin"),
	url(r'^company_admin/(?P<goal>[\w|\W]+)/(?P<company_id>[0-9]+)/$', views.editCompany_admin, name="editCompany_admin"),
	url(r'^viewmyprofile/?$', views.viewMyprofile_company, name="viewmyProfile_company"),
	url(r'^viewmyprofile_investor/?$', views.viewMyprofile_investor, name="viewmyProfile_investor"),
	url(r'^goal/?$', views.goalChoose, name="goalChoose"),
	url(r'^deletefile/(?P<goal>[\w|\W]+)/(?P<fid>[0-9]+)/$', views.deleteFile, name="deleteFile"),
	url(r'^google22cffa4b9737b2ae.html',TemplateView.as_view(template_name='mainsite/google22cffa4b9737b2ae.html'),)
]

mainsite/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mainsite/forms.py
from django import forms
from haystack.forms import SearchForm
from userprofile.models import bizCategory, bizGoal

class CompanySearchForm(SearchForm):
	category = forms.ModelChoiceField(queryset=bizCategory.objects.all(),required=False,empty_label="All Categories")
	goal = forms.ModelChoiceField(queryset=bizGoal.objects.all(),required=False,empty_label="All Goal")
	def serch(self):
		sqs = super(CompanySearchForm, self).search()
		if not self.is_valid():
			return self.no_query_found()
		# return self.no_query_found()

		if self.cleaned_data['category']:
			sqs = sqs.filter(category=self.cleaned_data['category'])
		if self.cleaned_data['goal']:
			sqs = sqs.filter(goal=bizGoal.objects.get(pk=self.cleaned_data['goal']))
		# sqs = None
		return sqs

userprofile/forms.py
from django import forms
from userprofile.models import *
import account.forms

class SignupForm(account.forms.SignupForm):
	fullname = forms.CharField(max_length=100,required=True)

	# roleChoice = ((1, 'Entrepreneur'),(2, 'Entrepreneur'),(3, 'Entrepreneur'))
	role = forms.ModelChoiceField(queryset=UserRole.objects.exclude(role='Admin'),required=True, empty_label=None)
	# role = forms.ChoiceField(choices=roleChoice)

class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['fullname','role','goal','country','state']

class GoalForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['goal']

class InvestorForm(forms.ModelForm):
	category = forms.ModelMultipleChoiceField(queryset=bizCategory.objects.all(),widget=forms.CheckboxSelectMultiple(),required=True)
	class Meta:
		model = InvestorProfile
		fields = ['category','name','iType','description','capital','preMoney_min','preMoney_max','expectedReturn','revenueStage_min','revenueStage_max','investAmount_min','investAmount_max','country','state']
		

class cpSeekFundForm(forms.ModelForm):
	category = forms.ModelMultipleChoiceField(queryset=bizCategory.objects.all(),widget=forms.CheckboxSelectMultiple(),required=True)
	class Meta:
		model = CompanyProfile_seekFund
		fields = ['category','name','description','capitalInvest','revenue','curNet','yearEstablished','employees','contactName','contactEmail','phone_number','website','country','state']

class cpSaleForm(forms.ModelForm):
	category = forms.ModelMultipleChoiceField(queryset=bizCategory.objects.all(),widget=forms.CheckboxSelectMultiple(),required=True)
	class Meta:
		model = CompanyProfile_sale
		fields = ['category','name','description','revenue','sales','profit','yearEstablished','employees','price','contactName','contactEmail','phone_number','website','country','state']

			

mainsite/views.py
import os
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.forms import formset_factory
from django.shortcuts import get_object_or_404

from django.contrib.contenttypes.models import ContentType

from haystack.generic_views import SearchView
from haystack.query import SearchQuerySet,EmptySearchQuerySet

from userprofile.models import *
from userprofile.forms import ProfileForm,InvestorForm,cpSeekFundForm, cpSaleForm,GoalForm
from mainsite.forms import CompanySearchForm

# Create your views here.
@login_required
def dashboard(request):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=2):
		return HttpResponseRedirect(reverse('mainsite:dashboard_investor'))
	if p.role == UserRole.objects.get(pk=4):
		return HttpResponseRedirect(reverse('mainsite:dashboard_admin'))
	#activeInvestor = Profile.objects.filter(isProfilecreated=True).filter(role=2,).order_by('-created_at').all()[:12]
	activeInvestor = Profile.objects.filter(role=2,).order_by('-created_at').all()[:12]
	context = {'activeInvestor':activeInvestor}
	return render(request,'mainsite/dashboard.html',context)

@login_required
def dashboard_investor(request):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=1):
		return HttpResponseRedirect(reverse('mainsite:dashboard'))
	if p.role == UserRole.objects.get(pk=4):
		return HttpResponseRedirect(reverse('mainsite:dashboard_admin'))
	interestCompany = CompanyProfile.objects.all().order_by('-created_at').all()[:12]
	# interestCompany = Profile.objects.filter(role=1,).order_by('-created_at').all()[:12]
	# if p.category.all().count() == 0:
	# 	interestCompany = Profile.objects.filter(role=1,).order_by('-created_at').all()[:12]
	# else:
	# 	interestCompany = Profile.objects.filter(category__in=p.category.all()).order_by('-created_at').all()[:12]
	# 	if interestCompany.count() == 0:
	# 		interestCompany = Profile.objects.filter(role=1,).order_by('-created_at').all()[:12]
	context = {'interestCompany':interestCompany}
	return render(request,'mainsite/dashboard_investor.html',context)

@login_required
def dashboard_admin(request):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=2):
		return HttpResponseRedirect(reverse('mainsite:dashboard_investor'))
	if p.role == UserRole.objects.get(pk=1):
		return HttpResponseRedirect(reverse('mainsite:dashboard'))
	investors = InvestorProfile.objects.filter(investor=request.user)
	companySale = CompanyProfile_sale.objects.filter(company=request.user)
	companySeek = CompanyProfile_seekFund.objects.filter(company=request.user)
	context = {'investors':investors, 'companySale':companySale,'companySeek':companySeek}
	return render(request,'mainsite/dashboard_admin.html',context)

@login_required
def editInvestors_admin(request,investor_id):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=1):
		return HttpResponseRedirect(reverse('mainsite:editProfile_company'))
	ip = InvestorProfile.objects.get(pk=investor_id)
	if request.method == 'POST':
		ip_form = InvestorForm(request.POST, instance=ip)
		if ip_form.is_valid():
			new_ip = ip_form.save(commit=False)
			new_ip.investor = request.user
			new_ip.save()
			ip_form.save_m2m()
			messages.success(request, "Investor's profile is successfullly updated.")
			#ip_form.save_m2m()
		return HttpResponseRedirect(reverse('mainsite:dashboard_admin'))
	else:
		ip_form =  InvestorForm(instance=ip)
	context = {'ip_form':ip_form,'tflag':"edit",'investor_id':investor_id}
	return render(request,'mainsite/editInvestors_admin.html',context)

@login_required
def addInvestors_admin(request):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=1):
		return HttpResponseRedirect(reverse('mainsite:editProfile_company'))
	# ip = InvestorProfile.objects.get(pk=investor_id)
	if request.method == 'POST':
		ip_form = InvestorForm(request.POST)
		if ip_form.is_valid():
			new_ip = ip_form.save(commit=False)
			new_ip.investor = request.user
			new_ip.save()
			ip_form.save_m2m()
			messages.success(request, "Investor's profile is successfullly updated.")
			#ip_form.save_m2m()
		return HttpResponseRedirect(reverse('mainsite:dashboard_investor'))
	else:
		ip_form =  InvestorForm()
	context = {'ip_form':ip_form}
	return render(request,'mainsite/editInvestors_admin.html',context)

@login_required
def  addCompany_admin(request,goal):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=2):
		return HttpResponseRedirect(reverse('mainsite:editProfile_investor'))
	
	if goal == "seek":
		ftag = 1
	else:
		# cp, created = CompanyProfile_sale.objects.get_or_create(company=request.user)
		ftag = 2
	#filesFormSet = formset_factory()
	#cp.name = p.fullname
	if request.method == 'POST':
		if ftag == 1:
			cp_form = cpSeekFundForm(request.POST)
		else:
			cp_form = cpSaleForm(request.POST)
			#profile_form.save_m2m()
		if cp_form.is_valid():
			companyprofile = cp_form.save(commit=False)
			companyprofile.goal = bizGoal.objects.get(pk=ftag)
			companyprofile.company = request.user
			companyprofile.save()
			cp_form.save_m2m()
			for afile in request.FILES.getlist('documents'):
				if ftag == 1:
					cf = CompanyFile_seek()
				else:
					cf = CompanyFile_sale()
				cf.companyprofile = companyprofile
				cf.file = afile
				cf.save()
			messages.success(request, 'Your profile is successfullly updated.')
		return HttpResponseRedirect(reverse('mainsite:dashboard_admin'))
		#return HttpResponseRedirect(reverse('mainsite:editProfile_company')) 
	else:
		if ftag == 1:
			cp_form = cpSeekFundForm()
		else:
			cp_form = cpSaleForm()
	isAdd = True
	context = {'cp_form':cp_form,'ftag':ftag,'isAdd':isAdd}
	return render(request,'mainsite/editcompany_admin.html',context)

@login_required
def editCompany_admin(request,goal,company_id):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=2):
		return HttpResponseRedirect(reverse('mainsite:editProfile_investor'))
	if goal == 'seek':
		cp = CompanyProfile_seekFund.objects.get(pk=company_id)
		ftag = 1
	else:
		cp = CompanyProfile_sale.objects.get(pk=company_id)
		ftag = 2
	print ftag
	if request.method == 'POST':
		if ftag == 1:
			cp_form = cpSeekFundForm(request.POST,instance=cp)
		else:
			cp_form = cpSaleForm(request.POST,instance=cp)	
		if cp_form.is_valid():
			companyprofile = cp_form.save(commit=False)
			companyprofile.goal = bizGoal.objects.get(pk=ftag)
			companyprofile.company = request.user
			companyprofile.save()
			cp_form.save_m2m()
			for afile in request.FILES.getlist('documents'):
				if ftag == 1:
					cf = CompanyFile_seek()
				else:
					cf = CompanyFile_sale()
				cf.companyprofile = companyprofile
				cf.file = afile
				cf.save()
			# gcp = CompanyProfile(content_object=companyprofile,created_at=companyprofile.created_at)
			# gcp.save()
			messages.success(request, 'Your profile is successfullly updated.')
		return HttpResponseRedirect(reverse('mainsite:dashboard_admin')) 
	else:
		if ftag == 1:
			cp_form = cpSeekFundForm(instance=cp)
			documents = CompanyFile_seek.objects.filter(companyprofile=cp)
		else:
			cp_form = cpSaleForm(instance=cp)
			documents = CompanyFile_sale.objects.filter(companyprofile=cp)
	isAdd = False
	context = {'cp_form':cp_form,'ftag':ftag,'isAdd':isAdd,'company_id':company_id,'documents':documents}
	return render(request,'mainsite/editcompany_admin.html',context)


@login_required
def goalChoose(request):
	p = request.user.myprofile
	if request.method == 'POST':
		goal_form = GoalForm(request.POST, instance=p)
		if goal_form.is_valid():
			profile = goal_form.save()
			profile.save()
		return HttpResponseRedirect(reverse('mainsite:editProfile_company'))
	else:
		goal_form = GoalForm(instance=p)
	context = {'goal_form':goal_form}
	return render(request,'mainsite/goalchoose.html',context)

@login_required
def viewMyprofile_company(request):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=2):
		return HttpResponseRedirect(reverse('mainsite:viewmyProfile_investor'))
	if p.goal is None:
		messages.error(request, "You haven't create your profile, please create it first")
		return HttpResponseRedirect('/goal/')
	if p.goal == bizGoal.objects.get(pk=1):
		cp, created = CompanyProfile_seekFund.objects.get_or_create(company=request.user)
		documents = CompanyFile_seek.objects.filter(companyprofile=cp)
		ftag = 1
	else:
		cp, created = CompanyProfile_sale.objects.get_or_create(company=request.user)
		documents = CompanyFile_sale.objects.filter(companyprofile=cp)
		ftag = 2
	context = {'profile':p,'cp':cp,'ftag':ftag,'documents':documents}
	return render(request,'mainsite/viewmyprofile_company.html',context)

@login_required
def viewMyprofile_investor(request):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=1):
		return HttpResponseRedirect(reverse('mainsite:viewmyProfile_company'))
	ip, created = InvestorProfile.objects.get_or_create(investor=request.user)
	if p.isProfilecreated is False:
		messages.error(request, "You haven't create your profile, please create it first")
		return HttpResponseRedirect(reverse('mainsite:editProfile_investor'))
	context = {'profile':p,'ip':ip}
	return render(request,'mainsite/viewmyprofile_investor.html',context)

@login_required
def editProfile_company(request):
	p = request.user.myprofile
	if p.role == UserRole.objects.get(pk=2):
		return HttpResponseRedirect(reverse('mainsite:editProfile_investor'))
	if p.goal is None:
		return HttpResponseRedirect('/goal/')
	elif p.goal == bizGoal.objects.get(pk=1):
		cp, created = CompanyProfile_seekFund.objects.get_or_create(company=request.user)
		ftag = 1
	else:
		cp, created = CompanyProfile_sale.objects.get_or_create(company=request.user)
		ftag = 2
	#filesFormSet = formset_factory()
	cp.name = p.fullname
	if request.method == 'POST':
		profile_form = ProfileForm(request.POST, instance=p)

mainsite/templates/mainsite/dashboard_admin.html
{% extends "site_base.html" %}
{% load i18n %}

{% block body %}
	<div class="col-lg-12"><h3>Hello {{ user.get_username }}</h3></div>
	<div class="col-md-4">
		<div class="panel panel-info">
			<div class="panel-heading">My Investors</div>
			<ul class="list-group">
				{% for investor in investors %}
				<li class="list-group-item">
					<h4><a href="{% url 'mainsite:editInvestors_admin' investor.id %}">{{investor.name}}</a></h4>
					<p>Signed up as an Investor on {{investor.created_at|date:"M d"}}</p>
					<p class=""></p>
				</li>
				{% endfor %}
			</ul>
			<a href="{% url 'mainsite:addInvestors_admin' %}" class="btn btn-outline btn-success col-md-12">Add New Investor</a>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-info">
			<div class="panel-heading">Company For Sale</div>
			<ul class="list-group">
				{% for sale in companySale %}
				<li class="list-group-item">
					<h4><a href="{% url 'mainsite:editCompany_admin' 'sale' sale.id %}">{{sale.name}}</a></h4>
					<p>Signed up as an Company for sale on {{sale.created_at|date:"M d"}}</p>
					<p class=""></p>
				</li>
				{% endfor %}
			</ul>
			<a href="{% url 'mainsite:addCompany_admin' 'sale' %}" class="btn btn-outline btn-success col-md-12">Add New</a>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-info">
			<div class="panel-heading">Company Seeking Investment</div>
			<ul class="list-group">
				{% for seek in companySeek %}
				<li class="list-group-item">
					<h4><a href="{% url 'mainsite:editCompany_admin' 'seek' seek.id %}">{{seek.name}}</a></h4>
					<p>Signed up as an Company seeking investment on {{seek.created_at|date:"M d"}}</p>
					<p class=""></p>
				</li>
				{% endfor %}
			</ul>
			<a href="{% url 'mainsite:addCompany_admin' 'seek' %}" class="btn btn-outline btn-success col-md-12">Add New</a>
		</div>
	</div>
{% endblock %}

mainsite/templates/mainsite/editInvestors_admin.html
{% extends "site_base.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block body %}
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-body">
					{% if tflag != "edit" %}
					<form role="form" method="post" action="{% url 'mainsite:addInvestors_admin'%}" enctype="multipart/form-data">
					{% else %}
					<form role="form" method="post" action="{% url 'mainsite:editInvestors_admin' investor_id %}" enctype="multipart/form-data">
					{% endif %}
					<div class="form-group">{% csrf_token %}</div>
					<div class="form-group">
						<label>Full Name</label>
						{% if ip_form.name.errors %}
							<div class="alert alert-danger" role="alert">
						    <ul>
						    {% for error in ip_form.name.errors %}
						        <li>{{ error|escape }}</li>
						    {% endfor %}
						    </ul>
						    </div>
						{% endif %}
						{% render_field ip_form.name class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Role</label>
						<select class="form-control" disabled="" id="id_role" name="role">
								<option value="">---------</option>
								<option value="1">Company</option>
								<option value="2" selected="selected">Investor</option>
								<option value="3">Supporter</option>
						</select>
					</div>
					<div class="form-group">
						<label>Investor Type</label>
						{% render_field ip_form.iType class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Industry</label>
						{{ ip_form.category.errors }} 
						{% render_field ip_form.category %}	
					</div>
					<div class="form-group">
						<label>Contry</label>
						{% render_field ip_form.country class="form-control" %}	
					</div>
					<div class="form-group">
						<label>State/ Province</label>
						{% render_field ip_form.state class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Detailed desription</label>
						{% render_field ip_form.description class="form-control" %}	
					</div>

					<div class="form-group">
						<label>Capital Type</label>
						{% render_field ip_form.capital class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Minimum Pre-Money Valuation of Interest</label>
						{% render_field ip_form.preMoney_min class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Maximum Pre-Money Valuation of Interest</label>
						{% render_field ip_form.preMoney_max class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Expected Rate of Return per Year(%)</label>
						{% render_field ip_form.expectedReturn class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Minimum Revenue Stage of Interest</label>
						{% render_field ip_form.revenueStage_min class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Maximum Revenue Stage of Interest</label>
						{% render_field ip_form.revenueStage_max class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Minimum Investment Range of Interest</label>
						{% render_field ip_form.investAmount_min class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Maximum Investment Range of Interest</label>
						{% render_field ip_form.investAmount_max class="form-control" %}	
					</div>
					<input type="submit" class="btn btn-lg btn-success btn-block" value="Submit" />
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

mainsite/templates/mainsite/editcompany_admin.html
{% extends "site_base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load filename %}

{% block body %}
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-body">
				{% if isAdd and ftag == 1 %}
				<form role="form" method="post" action="{% url 'mainsite:addCompany_admin' 'seek' %}" enctype="multipart/form-data">
				{% elif isAdd and ftag == 2 %}
				<form role="form" method="post" action="{% url 'mainsite:addCompany_admin' 'sale' %}" enctype="multipart/form-data">
				{% elif not isAdd and ftag == 1 %}
				<form role="form" method="post" action="{% url 'mainsite:editCompany_admin' 'seek' company_id%}" enctype="multipart/form-data">
				{% elif not isAdd and ftag == 2 %}
				<form role="form" method="post" action="{% url 'mainsite:editCompany_admin' 'sale' company_id%}" enctype="multipart/form-data">
				{% endif %}
					<div class="form-group">{% csrf_token %}</div>
					<div class="form-group">
						<label>Full Name</label>
						{% if cp_form.name.errors %}
							<div class="alert alert-danger" role="alert">
						    <ul>
						    {% for error in cp_form.name.errors %}
						        <li>{{ error|escape }}</li>
						    {% endfor %}
						    </ul>
						    </div>
						{% endif %}
						{% render_field cp_form.name class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Role</label>
						<select class="form-control" disabled="" id="id_role" name="role">
								<option value="">---------</option>
								<option value="1" selected="selected">Company</option>
								<option value="2">Investor</option>
								<option value="3">Supporter</option>
						</select>
					</div>
					<div class="form-group">
						<label>Purpose</label>
						<select class="form-control" disabled="" id="id_goal" name="goal">
							<option value="">---------</option>
							<option value="2" {% if ftag == 2 %}selected="selected"{% endif %}>Company for Sale</option>
							<option value="1" {% if ftag == 1 %}selected="selected"{% endif %}>Look for Funding</option>
						</select>
					</div>
					<div class="form-group">
						<label>Industry</label>
						{{ cp_form.category.errors }} 
						{% render_field cp_form.category %}	
					</div>
					<div class="form-group">
						<label>Country</label>
						{% render_field cp_form.country class="form-control" %}	
					</div>
					<div class="form-group">
						<label>State/ Province</label>
						{% render_field cp_form.state class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Introduction</label>
						{% render_field cp_form.description class="form-control" %}	
					</div>
					{% if ftag == 1 %}
					<div class="form-group">
						<label>Capital Invest</label>
						{% render_field cp_form.capitalInvest class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Revenue</label>
						{% render_field cp_form.revenue class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Current Net Income</label>
						{% render_field cp_form.curNet class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Year Established</label>
						{% render_field cp_form.yearEstablished class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Employees</label>
						{% render_field cp_form.employees class="form-control" %}	
					</div>
					{% endif %}
					{% if ftag == 2 %}
					<div class="form-group">
						<label>Revenue</label>
						{% render_field cp_form.revenue class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Sales</label>
						{% render_field cp_form.sales class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Profit</label>
						{% render_field cp_form.profit class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Year Established</label>
						{% render_field cp_form.yearEstablished class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Employees</label>
						{% render_field cp_form.employees class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Asking Price</label>
						{% render_field cp_form.price class="form-control" %}	
					</div>
					{% endif %}
					<div class="form-group">
						<label>Contact Name</label>
						{% render_field cp_form.contactName class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Contact Email</label>
						{% render_field cp_form.contactEmail class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Phone Number</label>
						{% render_field cp_form.phone_number class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Website</label>
						{% render_field cp_form.website class="form-control" %}	
					</div>
					<div class="form-group">
						<label>Add Documents</label>
						<input type="file" name="documents">
						<input type="file" name="documents">
						<input type="file" name="documents">
					</div>
					{% if documents %}
					<div class="form-group">
						<label>Current Documents on Record</label>
						{% for d in documents %}
						<li><a href="{{ d.file.url }}">{{ d.file|filename}}</a>&nbsp;&nbsp;&nbsp;
						{% if ftag == 1 %}
						<a href="{% url 'mainsite:deleteFile' 'seek' d.pk %}?q={{ request.build_absolute_uri }}" class="text-danger">Delete</a>
						{% else %}
						<a href="{% url 'mainsite:deleteFile' 'sale' d.pk %}?q={{ request.build_absolute_uri }}" class="text-danger">Delete</a>
						{% endif %}
						</li>
						{% endfor %}
					</div>
					{% endif %}
					<!-- <input type="file" name="myfiles" multiple> -->
					<input type="submit" class="btn btn-lg btn-success btn-block" value="Submit" />
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

mainsite/templates/mainsite/google22cffa4b9737b2ae.html
google-site-verification: google22cffa4b9737b2ae.html