Kerrgo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
import userprofile.views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/signup/$", userprofile.views.SignupView.as_view(), name="account_signup"),
    url(r"^account/", include("account.urls")),
    url(r'^messages/', include('postman.urls')),
    url(r'^',include('mainsite.urls', namespace="mainsite")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.conf.urls import include,url
# from . import views
from . import views
from django.views.generic import TemplateView

urlpatterns = [
	#url(r'^search/?$', views.MySearchView.as_view(), name='mysearch'),
	url(r'^search/?$', views.my_basic_search, name="mysearch"),
	# url(r'^search/', include('haystack.urls')),
	url(r'^viewcompany/(?P<goal>[\w|\W]+)/(?P<company_id>[0-9]+)/$',views.viewCompany, name='viewCompany'),
	url(r'^investor/(?P<user_id>[0-9]+)/$',views.viewInvestor, name='viewInvestor'),
	url(r'^investors/(?P<type_name>[\w|\W]+)/$',views.browseInvestor, name='browseInvestor'),
	url(r'^companies/(?P<goal_name>[\w|\W]+)/$',views.browseCompany, name='browseCompany'),
	url(r'^dashboard/?$', views.dashboard, name="dashboard"),
	url(r'^dashboard_investor/?$', views.dashboard_investor, name="dashboard_investor"),
	url(r'^dashboard_admin/?$', views.dashboard_admin, name="dashboard_admin"),
	url(r'^editprofile/?$', views.editProfile_company, name="editProfile_company"),
	url(r'^editprofile_investor/?$', views.editProfile_investor, name="editProfile_investor"),
	url(r'^investor_admin/(?P<investor_id>[0-9]+)/$', views.editInvestors_admin, name="editInvestors_admin"),
	url(r'^addinvestor_admin/?$', views.addInvestors_admin, name="addInvestors_admin"),
	url(r'^addcompany_admin/(?P<goal>[\w|\W]+)/$', views.addCompany_admin, name="addCompany_admin"),
	url(r'^company_admin/(?P<goal>[\w|\W]+)/(?P<company_id>[0-9]+)/$', views.editCompany_admin, name="editCompany_admin"),
	url(r'^viewmyprofile/?$', views.viewMyprofile_company, name="viewmyProfile_company"),
	url(r'^viewmyprofile_investor/?$', views.viewMyprofile_investor, name="viewmyProfile_investor"),
	url(r'^goal/?$', views.goalChoose, name="goalChoose"),
	url(r'^deletefile/(?P<goal>[\w|\W]+)/(?P<fid>[0-9]+)/$', views.deleteFile, name="deleteFile"),
	url(r'^google22cffa4b9737b2ae.html',TemplateView.as_view(template_name='mainsite/google22cffa4b9737b2ae.html'),)
]

Kerrgo/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}
{% load postman_tags %}

<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> {% user_display request.user %} <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li><a href="{% url 'account_settings' %}"><i class="fa fa-cog fa-fw"></i> {% trans "Settings" %}</a>
            </li>
            <li class="divider"></li>
            <li><a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off fa-fw"></i> {% trans "Log out" %}</a>
            </li>
          </ul>
        </li>
        <li>
            <a href="{% url 'mainsite:dashboard' %}"><i class="fa fa-tachometer"></i> {% trans "Dashboard" %}</a>
        </li>
        <!-- .dropdown-messages -->
        <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-envelope fa-fw"></i>  
                 {% trans "Messages" %}
                 <i class="fa fa-caret-down"></i>
                <!-- Dropdown <span class="caret"></span> -->
              </a>
              <ul class="dropdown-menu dropdown-messages">
                <li>
                  <a href="{% url 'postman_inbox' %}">
                    <div>
                      <i class="fa fa-comment fa-fw"></i>
                      {% trans "Inbox" %}
                      {% postman_unread as unread_count %}
                      {% if unread_count %}
                      <!-- <span class="pull-right text-muted small"> -->
                      <span class = "badge pull-right">
                        {{ unread_count }}
                      </span>
                      {% endif %}
                    </div>  
                  </a>
                </li>
                <li class="divider"></li>

                <li>
                  <a href="{% url 'postman_sent' %}">
                    <div>
                      <i class="fa fa-envelope fa-fw"></i>
                      {% trans "Messages Sent" %}
                    </div>  
                  </a>
                </li>
                <li class="divider"></li>

                <li>
                  <a href="{% url 'postman_write' %}">
                    <div>
                      <i class="fa fa-twitter fa-fw"></i>
                      {% trans "Write Message" %}
                    </div>  
                  </a>
                </li>
                <li class="divider"></li>

                <li>
                  <a href="{% url 'postman_archives' %}">
                    <div>
                      <i class="fa fa-archive fa-fw"></i>
                      {% trans "Archives" %}
                    </div>  
                  </a>
                </li>
                <li class="divider"></li>

                <li>
                  <a href="{% url 'postman_trash' %}">
                    <div>
                      <i class="fa fa-bitbucket fa-fw"></i>
                      {% trans "Trash" %}
                    </div>  
                  </a>
                </li>
              </ul>
            </li>
            <!-- /.dropdown-messages -->
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

Kerrgo/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2016 &lt;Kerrgo&gt;" %}

Kerrgo/templates/_scripts.html
<script src='/site_media/static/js/site-5e73bbeeb0.js'></script>

Kerrgo/templates/_styles.html
<link href='/site_media/static/css/site-e7b87bbea0.css' rel='stylesheet' />

Kerrgo/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Home{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
{% comment "Optional Slider" %}
<div id="myCarouselSlider" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarouselSlider" data-slide-to="0" class="active"></li>
        <li data-target="#myCarouselSlider" data-slide-to="1" class=""></li>
        <li data-target="#myCarouselSlider" data-slide-to="2" class=""></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide slider_img" src="http://ridhomuhammadsakti.com/wp-content/uploads/2015/02/rtv-tools-slider-background.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="{% url 'account_signup' %}" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide slider_img" src="http://www.citadelny.com/wp-content/uploads/2014/01/citadel-slider-background-cloud-1.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Our Partners</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="{% url 'browsepartners' %}" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide slider_img" src="http://competitivenaturalgas.com/wp-content/uploads/2014/04/Slider-Background-city.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Projects</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="{% url 'mainsite:browseProject' 'ALL' %}" role="button">Browse Projects</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarouselSlider" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarouselSlider" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    {% endcomment %}
    <!-- Main Body  -->
    <div class="container" role="main">

      <h2 class = "text-center">JOIN OUR EXCLUSIVE INVESTOR NETWORK</h2>
      <hr>
      <!-- <h4 class="text-center">WE ARE PLEASED TO OFFER BOTH ACCREDITED AND NON-ACCREDITED U.S. INVESTORS* THE OPPORTUNITY TO BE INCLUDED IN OUR DEAL FLOW</h4> -->
      <p class="text-center">We provide a myriad of value-added services for both Chinese funds/investors who are investing in U.S. /Israel companies/technologies</p>
      <p class="text-center">As well as </p>
      <p class="text-center">U.S./ Israel companies who are looking for investors, strategic partners, market entrance to China or sell its companies or transfer its technologies</p>
      <div class="marketing">
        <!-- Three columns of text below the carousel -->
        <div class="row">
          <div class="col-md-2 col-md-offset-1">
            <img class="img-circle" src="http://chasmic-research.com/wp-content/uploads/2014/07/Business-Plan.jpg" alt="Generic placeholder image" width="140" height="140">
            <h3>SELL YOUR COMPANY</h2>
            <p>List your company and we help you find the best buyers</p>
            <!-- <p><a class="btn btn-default" href="#" role="button">View details »</a></p> -->
          </div><!-- /.col-lg-4 -->
          <div class="col-md-2">
            <img class="img-circle" src="http://www.filminvesting.net/wp-content/uploads/2015/03/Invest.jpg" alt="Generic placeholder image" width="140" height="140">
            <h3>LOOK FOR INVESTORS</h2>
            <p>We have all the major funds and private investors as our partner, please upload your company profile and business executives summary</p>
            <!-- <p><a class="btn btn-default" href="#" role="button">View details »</a></p> -->
          </div><!-- /.col-lg-4 -->
          <div class="col-md-2">
            <img class="img-circle" src="http://www.ideabuyer.com/news/wp-content/uploads/2008/10/patentlicensingnegotiations.png" alt="Generic placeholder image" width="140" height="140">
            <h3>TECHNOLOGY LICENSING </h2>
            <p>If you want to transfer or license your technology.  Please list your company profile and technology for Chinese companies and investors to find you</p>
            <!-- <p><a class="btn btn-default" href="#" role="button">View details »</a></p> -->
          </div><!-- /.col-lg-4 -->
          <div class="col-md-2">
            <img class="img-circle" src="http://www.billgenie.com/assets/images/gsi_strategic_partners_cropped.jpg" alt="Generic placeholder image" width="140" height="140">
            <h3>LOOK FOR STRATEGIC PARTNER  </h2>
            <p></p>
            <!-- <p><a class="btn btn-default" href="#" role="button">View details »</a></p> -->
          </div><!-- /.col-lg-4 -->
          <div class="col-md-2">
            <img class="img-circle" src="http://webber.edu/wp-content/uploads/2015/05/marketing.png" alt="Generic placeholder image" width="140" height="140">
            <h3>MARKET ENTRANCE </h2>
            <p></p>
            <!-- <p><a class="btn btn-default" href="#" role="button">View details »</a></p> -->
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


          <!-- START THE FEATURETTES -->

          <!-- <hr class="featurette-divider"> -->

              <!-- <div class="row featurette">
                <div class="col-md-7">
                  <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
                  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                </div>
                <div class="col-md-5">
                  <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
                </div>
              </div>

              <hr class="featurette-divider">

              <div class="row featurette">
                <div class="col-md-7 col-md-push-5">
                  <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
                  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                </div>
                <div class="col-md-5 col-md-pull-7">
                  <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
                </div>
              </div>

              <hr class="featurette-divider">

              <div class="row featurette">
                <div class="col-md-7">
                  <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
                  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                </div>
                <div class="col-md-5">
                  <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
                </div>
              </div>

              <hr class="featurette-divider"> -->

              <!-- /END THE FEATURETTES -->
      </div>
{% endblock %}

Kerrgo/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load metron_tags %}
{% load i18n %}


{% block styles %}
    {% include "_styles.html" %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}

{% block topbar_base %}
<header>
	<div class="navbar navbar-inverse {% block navbar_class %}navbar-fixed-top{% endblock %}">
		<div class="container">
			{% block topbar %}
			<div class="navbar-header">
				<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="fa fa-bars"></span>
				</button>
				{% block site_brand %}<a class="navbar-brand" href="{% url "home" %}">Kerrgo</a>{% endblock %}
			</div>
			<div class="collapse navbar-collapse navbar-responsive-collapse">
				{% block nav %}
				<ul class="nav navbar-nav">
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Companies<span class="caret"></span></a>
					  <ul class="dropdown-menu">
					  	<li><a href="{% url 'mainsite:browseCompany' 'all' %}">All Companies</a></li>
					  	<li><a href="{% url 'mainsite:browseCompany' 'seek' %}">Seek Investor</a></li>
					  	<li><a href="{% url 'mainsite:browseCompany' 'sale' %}">Sell Company</a></li>
					  </ul>
					</li>
					<li><a href="{% url 'mainsite:browseInvestor' 'ALL' %}">Investors</a></li>
				</ul>
				{% endblock %}
				{% block account_bar %}{% include "_account_bar.html" %}{% endblock %}
			</div>
			{% endblock %}

		</div>
		{% block nav_sidebar %}{% endblock %}
	</div>
</header>
{% endblock %}